package cr.casino.catalogoCasino.domain;
// Generated 19/09/2018 07:56:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * BdcAgente generated by hbm2java
 */
public class BdcAgente  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String zona;
     private String estatus;
     private String telefono;
     private List<BdcPedido> bdcPedidos;


    public BdcAgente() {
    }

	
    public BdcAgente(String codigo) {
        this.codigo = codigo;
    }
    public BdcAgente(String codigo, String nombre, String zona, String estatus, String telefono, List<BdcPedido> bdcPedidos) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.zona = zona;
       this.estatus = estatus;
       this.telefono = telefono;
       this.bdcPedidos = bdcPedidos;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public List<BdcPedido> getBdcPedidos() {
        return this.bdcPedidos;
    }
    
    public void setBdcPedidos(List<BdcPedido> bdcPedidos) {
        this.bdcPedidos = bdcPedidos;
    }
}


