package cr.casino.catalogoCasino.domain;
// Generated 19/09/2018 07:56:15 PM by Hibernate Tools 4.3.1



/**
 * BdcAgenteAuxiliar generated by hbm2java
 */
public class BdcAgenteAuxiliar  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String zona;
     private String estatus;
     private String telefono;

    public BdcAgenteAuxiliar() {
    }

	
    public BdcAgenteAuxiliar(String codigo) {
        this.codigo = codigo;
    }
    public BdcAgenteAuxiliar(String codigo, String nombre, String zona, String estatus, String telefono) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.zona = zona;
       this.estatus = estatus;
       this.telefono = telefono;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


