package cr.casino.catalogoCasino.domain;
// Generated 19/09/2018 07:56:15 PM by Hibernate Tools 4.3.1



/**
 * BdcClienteAuxiliar generated by hbm2java
 */
public class BdcClienteAuxiliar  implements java.io.Serializable {


     private String cliente;
     private String vendedor;
     private String nombre;
     private String poblacion;
     private String codigo;
     private String nombre2;
     private String calle;
     private String poblacion2;
     private String region;
     private String telefono;

    public BdcClienteAuxiliar() {
    }

	
    public BdcClienteAuxiliar(String cliente) {
        this.cliente = cliente;
    }
    public BdcClienteAuxiliar(String cliente, String vendedor, String nombre, String poblacion, String codigo, String nombre2, String calle, String poblacion2, String region, String telefono) {
       this.cliente = cliente;
       this.vendedor = vendedor;
       this.nombre = nombre;
       this.poblacion = poblacion;
       this.codigo = codigo;
       this.nombre2 = nombre2;
       this.calle = calle;
       this.poblacion2 = poblacion2;
       this.region = region;
       this.telefono = telefono;
    }
   
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre2() {
        return this.nombre2;
    }
    
    public void setNombre2(String nombre2) {
        this.nombre2 = nombre2;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getPoblacion2() {
        return this.poblacion2;
    }
    
    public void setPoblacion2(String poblacion2) {
        this.poblacion2 = poblacion2;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


