package cr.casino.catalogoCasino.domain;
// Generated 19/09/2018 07:56:15 PM by Hibernate Tools 4.3.1



/**
 * BdcDetallePedidoId generated by hbm2java
 */
public class BdcDetallePedidoId  implements java.io.Serializable {


     private String pedido;
     private String producto;

    public BdcDetallePedidoId() {
    }

    public BdcDetallePedidoId(String pedido, String producto) {
       this.pedido = pedido;
       this.producto = producto;
    }
   
    public String getPedido() {
        return this.pedido;
    }
    
    public void setPedido(String pedido) {
        this.pedido = pedido;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BdcDetallePedidoId) ) return false;
		 BdcDetallePedidoId castOther = ( BdcDetallePedidoId ) other; 
         
		 return ( (this.getPedido()==castOther.getPedido()) || ( this.getPedido()!=null && castOther.getPedido()!=null && this.getPedido().equals(castOther.getPedido()) ) )
 && ( (this.getProducto()==castOther.getProducto()) || ( this.getProducto()!=null && castOther.getProducto()!=null && this.getProducto().equals(castOther.getProducto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPedido() == null ? 0 : this.getPedido().hashCode() );
         result = 37 * result + ( getProducto() == null ? 0 : this.getProducto().hashCode() );
         return result;
   }   


}


