package cr.casino.catalogoCasino.domain;
// Generated 19/09/2018 07:56:15 PM by Hibernate Tools 4.3.1



/**
 * BdcDetallePedido generated by hbm2java
 */
public class BdcDetallePedido  implements java.io.Serializable {


     private BdcDetallePedidoId id;
     private BdcPedido bdcPedido;
     private BdcProducto bdcProducto;

    public BdcDetallePedido() {
    }

	
    public BdcDetallePedido(BdcDetallePedidoId id) {
        this.id = id;
    }
    public BdcDetallePedido(BdcDetallePedidoId id, BdcPedido bdcPedido, BdcProducto bdcProducto) {
       this.id = id;
       this.bdcPedido = bdcPedido;
       this.bdcProducto = bdcProducto;
    }
   
    public BdcDetallePedidoId getId() {
        return this.id;
    }
    
    public void setId(BdcDetallePedidoId id) {
        this.id = id;
    }
    public BdcPedido getBdcPedido() {
        return this.bdcPedido;
    }
    
    public void setBdcPedido(BdcPedido bdcPedido) {
        this.bdcPedido = bdcPedido;
    }
    public BdcProducto getBdcProducto() {
        return this.bdcProducto;
    }
    
    public void setBdcProducto(BdcProducto bdcProducto) {
        this.bdcProducto = bdcProducto;
    }




}


