package cr.casino.catalogoCasino.domain;
// Generated 19/09/2018 07:56:15 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BdcReserva generated by hbm2java
 */
public class BdcReserva  implements java.io.Serializable {


     private String codigo;
     private BdcPedido bdcPedido;
     private Date fechaInicio;
     private Date fechaLimite;

    public BdcReserva() {
    }

	
    public BdcReserva(String codigo) {
        this.codigo = codigo;
    }
    public BdcReserva(String codigo, BdcPedido bdcPedido, Date fechaInicio, Date fechaLimite) {
       this.codigo = codigo;
       this.bdcPedido = bdcPedido;
       this.fechaInicio = fechaInicio;
       this.fechaLimite = fechaLimite;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public BdcPedido getBdcPedido() {
        return this.bdcPedido;
    }
    
    public void setBdcPedido(BdcPedido bdcPedido) {
        this.bdcPedido = bdcPedido;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaLimite() {
        return this.fechaLimite;
    }
    
    public void setFechaLimite(Date fechaLimite) {
        this.fechaLimite = fechaLimite;
    }




}


