package cr.casino.catalogoCasino.domain;
// Generated 19/09/2018 07:56:15 PM by Hibernate Tools 4.3.1



/**
 * BdcUsuarioAgente generated by hbm2java
 */
public class BdcUsuarioAgente  implements java.io.Serializable {


     private String codigoAgente;
     private BdcAgente bdcAgente;
     private String contrasena;

    public BdcUsuarioAgente() {
    }

	
    public BdcUsuarioAgente(BdcAgente bdcAgente) {
        this.bdcAgente = bdcAgente;
    }
    public BdcUsuarioAgente(BdcAgente bdcAgente, String contrasena) {
       this.bdcAgente = bdcAgente;
       this.contrasena = contrasena;
    }
   
    public String getCodigoAgente() {
        return this.codigoAgente;
    }
    
    public void setCodigoAgente(String codigoAgente) {
        this.codigoAgente = codigoAgente;
    }
    public BdcAgente getBdcAgente() {
        return this.bdcAgente;
    }
    
    public void setBdcAgente(BdcAgente bdcAgente) {
        this.bdcAgente = bdcAgente;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }




}


